/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Brush: typeof import('./src/components/Brush.vue')['default']
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    FileManager: typeof import('./src/components/FileManager.vue')['default']
    ImageManager: typeof import('./src/components/ImageManager.vue')['default']
    Midi: typeof import('./src/components/Midi.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RulePicker: typeof import('./src/components/RulePicker.vue')['default']
    Slider: typeof import('./src/components/Slider.vue')['default']
    Universe: typeof import('./src/components/Universe.vue')['default']
    Viewport: typeof import('./src/components/Viewport.vue')['default']
  }
}
