/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Brush: typeof import('./src/components/Brush.vue')['default']
    CA: typeof import('./src/components/CA.vue')['default']
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    FileManager: typeof import('./src/components/FileManager.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    Midi: typeof import('./src/components/Midi.vue')['default']
    MidiListeners: typeof import('./src/components/MidiListeners.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RulePicker: typeof import('./src/components/RulePicker.vue')['default']
    Rules: typeof import('./src/components/Rules.vue')['default']
    Slider: typeof import('./src/components/Slider.vue')['default']
    Universe: typeof import('./src/components/Universe.vue')['default']
    Viewport: typeof import('./src/components/Viewport.vue')['default']
  }
}
